-- Blackshear PTA - the five announcements that were markdown files in git.
--
-- GENERATED by scripts/build-import-migration.mjs from
-- src/content/announcements/*.md. Do not hand-edit: regenerate it.
--
-- Safe to re-run. The posts are OR IGNORE on the slug primary key and the
-- audit rows are guarded by NOT EXISTS, so a second application is a no-op.
-- Note that OR IGNORE does not disarm the schema triggers: a post with a
-- missing alt text or a cover that is not one of its own images still fails
-- loudly rather than arriving half-formed.
--
-- Slugs are the markdown filenames minus ".md", so every URL is unchanged.

-- src/content/announcements/2026-07-30-save-blackshear.md
INSERT OR IGNORE INTO posts
  (slug, title, date, href, link_label, images, cover, grades, pinned, draft, body, created_at, updated_at)
VALUES (
  '2026-07-30-save-blackshear',
  'Let''s keep Blackshear where it is',
  '2026-07-30',
  'https://www.saveblackshear.org',
  'Read more at saveblackshear.org',
  '[]',
  NULL,
  '[]',
  1,
  0,
  'Our campus has been part of this neighbourhood for 135 years. There is an
organized effort to keep it here for the next 135, and it is worth your
attention.

A neighbourhood school is not only a building. It is the reason children walk
to school, the reason families meet each other, and a large part of what makes
this part of East Austin feel like somewhere rather than anywhere.

The campaign has the detail, including how to help.',
  '2026-07-30T00:00:00Z',
  '2026-07-30T00:00:00Z'
);

INSERT INTO edits (at, editor, action, slug, title, detail)
SELECT '2026-07-30T00:00:00Z', 'src/content/announcements (git)', 'import', '2026-07-30-save-blackshear', 'Let''s keep Blackshear where it is',
       '{"source":"src/content/announcements/2026-07-30-save-blackshear.md"}'
WHERE NOT EXISTS (SELECT 1 FROM edits WHERE slug = '2026-07-30-save-blackshear' AND action = 'import');

-- src/content/announcements/2026-08-05-no-sting-3.md
INSERT OR IGNORE INTO posts
  (slug, title, date, href, link_label, images, cover, grades, pinned, draft, body, created_at, updated_at)
VALUES (
  '2026-08-05-no-sting-3',
  'No Sting Fundraiser #3 was a success',
  '2026-08-05',
  'https://tinyurl.com/Donate2Blackshear',
  'Make a donation',
  '[]',
  NULL,
  '[]',
  0,
  0,
  'The final numbers are in and we hit our goal. Thank you to everyone who gave.

"No Sting" means exactly what it sounds like: no wrapping paper, no catalogues,
no asking your family to buy things nobody wanted. You give directly, all of it
goes to the PTA, and we skip the part where a company takes a cut.

Missed it? You can still make a general donation, or help us keep classrooms
stocked with supplies.',
  '2026-08-05T00:00:00Z',
  '2026-08-05T00:00:00Z'
);

INSERT INTO edits (at, editor, action, slug, title, detail)
SELECT '2026-08-05T00:00:00Z', 'src/content/announcements (git)', 'import', '2026-08-05-no-sting-3', 'No Sting Fundraiser #3 was a success',
       '{"source":"src/content/announcements/2026-08-05-no-sting-3.md"}'
WHERE NOT EXISTS (SELECT 1 FROM edits WHERE slug = '2026-08-05-no-sting-3' AND action = 'import');

-- src/content/announcements/2026-08-14-buzz-bowl.md
INSERT OR IGNORE INTO posts
  (slug, title, date, href, link_label, images, cover, grades, pinned, draft, body, created_at, updated_at)
VALUES (
  '2026-08-14-buzz-bowl',
  'The Literacy Buzz Bowl returns',
  '2026-08-14',
  NULL,
  NULL,
  '[]',
  NULL,
  '["3","4","5"]',
  0,
  0,
  'Our own take on Battle of the Books is back, and the PTA is sponsoring it again
this year.

Here is how it works. Parent volunteers read with 3rd, 4th and 5th graders in
the weeks beforehand. Students then compete in a trivia showdown on the books
they have read, and everyone celebrates afterwards with ice cream and donuts.

It is one of the easiest things to volunteer for. You read with kids, which is
the good part, and you do not need any experience to do it.

Watch for sign-ups closer to the date.',
  '2026-08-14T00:00:00Z',
  '2026-08-14T00:00:00Z'
);

INSERT INTO edits (at, editor, action, slug, title, detail)
SELECT '2026-08-14T00:00:00Z', 'src/content/announcements (git)', 'import', '2026-08-14-buzz-bowl', 'The Literacy Buzz Bowl returns',
       '{"source":"src/content/announcements/2026-08-14-buzz-bowl.md"}'
WHERE NOT EXISTS (SELECT 1 FROM edits WHERE slug = '2026-08-14-buzz-bowl' AND action = 'import');

-- src/content/announcements/2026-08-20-135-years.md
INSERT OR IGNORE INTO posts
  (slug, title, date, href, link_label, images, cover, grades, pinned, draft, body, created_at, updated_at)
VALUES (
  '2026-08-20-135-years',
  '135 years in East Austin',
  '2026-08-20',
  'https://tinyurl.com/BlackshearATXplained',
  'Listen to the ATXplained story',
  '[]',
  NULL,
  '[]',
  0,
  0,
  'Blackshear is celebrating 135 years, and KUT''s ATXplained confirmed what we
suspected: it is Austin''s oldest continuously operating elementary school.

The school opened in 1891 and has been part of this neighbourhood ever since,
through every change East Austin has been through. KVUE covered the celebration
as well.

It is worth saying out loud what that means. Children have been walking through
those doors for longer than anyone reading this has been alive, and the PTA''s
job is to make sure that keeps being true.',
  '2026-08-20T00:00:00Z',
  '2026-08-20T00:00:00Z'
);

INSERT INTO edits (at, editor, action, slug, title, detail)
SELECT '2026-08-20T00:00:00Z', 'src/content/announcements (git)', 'import', '2026-08-20-135-years', '135 years in East Austin',
       '{"source":"src/content/announcements/2026-08-20-135-years.md"}'
WHERE NOT EXISTS (SELECT 1 FROM edits WHERE slug = '2026-08-20-135-years' AND action = 'import');

-- src/content/announcements/2026-09-02-test-post-garden.md
INSERT OR IGNORE INTO posts
  (slug, title, date, href, link_label, images, cover, grades, pinned, draft, body, created_at, updated_at)
VALUES (
  '2026-09-02-test-post-garden',
  'Garden work day coming up',
  '2026-09-02',
  NULL,
  NULL,
  '[{"key":"0022d9a93370c18877eac7661bb92a93.jpg","alt":"Garden day"},{"key":"2ae672a58adafa1440f211e14eb1ecc5.jpg","alt":"Test"},{"key":"72fba0b8249d250ca513d203cd034df7.jpg","alt":"Test2"}]',
  '0022d9a93370c18877eac7661bb92a93.jpg',
  '[]',
  0,
  1,
  'A garden work day is coming up. Bring gloves if you have them; we have spares
if you do not.

Work days are the easiest way into the Campus Beautification committee. Show up,
and there is always something to do.',
  '2026-09-02T00:00:00Z',
  '2026-09-02T00:00:00Z'
);

INSERT INTO edits (at, editor, action, slug, title, detail)
SELECT '2026-09-02T00:00:00Z', 'src/content/announcements (git)', 'import', '2026-09-02-test-post-garden', 'Garden work day coming up',
       '{"source":"src/content/announcements/2026-09-02-test-post-garden.md"}'
WHERE NOT EXISTS (SELECT 1 FROM edits WHERE slug = '2026-09-02-test-post-garden' AND action = 'import');
